const allowedExtensions = {
  image: ['jpg', 'jpeg', 'png', 'gif'],
  video: ['mp4', 'avi', 'mkv'],
  audio: ['mp3', 'wav'],
  doc: [
    'doc',
    'docx',
    'xls',
    'xlsx',
    'ppt',
    'pptx',
    'pdf',
    'odt',
    'odp',
    'ods',
    'odg',
    'odf',
    'rtf',
    'txt',
    'csv',
    'ods',
    'xls',
    'xlsx',
    'ppt',
    'pptx',
    'pdf',
    'odt',
    'odp',
    'ods',
    'odg',
    'odf',
    'rtf',
    'txt',
    'csv',
  ],
  zip: ['zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'xz'],
  code: ['js', 'jsx', 'ts', 'tsx', 'html', 'css', 'scss', 'json', 'xml'],
};

export default allowedExtensions;
